version: '2'
services:
  node01:
    image: aritranag20/spring-boot-mongo-es
    restart: always
    environment:
      - TZ=America/Montreal
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://54.152.114.46:5010"
        syslog-format: "rfc3164"
        tag: "node-01"
    ports:
      - '8000:8000'
